name: CI
on:
  pull_request:
  push:
    branches: [ master, main, "feat/**" ]
jobs:
  api-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r apps/api/requirements.txt
      - name: Lint syntax
        run: python -m py_compile apps/api/*.py apps/api/**/*.py
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install & Build
        run: |
          pnpm -C apps/web install
          pnpm -C apps/web build
